browser=chrome
url=https://automationexercise.com/
api.base.url=https://automationexercise.com/
email=usertest41@gmail.com
password=Usertest@41

db.url=jdbc:mysql://localhost:3306/ecommerce
db.username=root
db.password=your_password